// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs1joIxC9utFrXdGm1dNOmZ3yFLz-Y13w',
    appId: '1:1022972424623:web:1db30b32588b59fab47f5a',
    messagingSenderId: '1022972424623',
    projectId: 'learntera-app',
    authDomain: 'learntera-app.firebaseapp.com',
    storageBucket: 'learntera-app.appspot.com',
    measurementId: 'G-VMZ4ETSW4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl93QbzZeOaU5DcrFGZnwgdLSXEaJV9nY',
    appId: '1:1022972424623:android:c152f7456a28b7ceb47f5a',
    messagingSenderId: '1022972424623',
    projectId: 'learntera-app',
    storageBucket: 'learntera-app.appspot.com',
  );
}
